### ISSUE TITLE
Remove 91.216.216.0/24 from client announcement options and filters

### ISSUE THREAD

**Issue by bschlinker** [PEERINGTestbed/client#1]

**Comment by cunha** [comment]
Roadline for fixing this:
- Fix client BGP config generation on back-end
- Implement automated pushes to this repository whenever the configuration changes (e.g., new prefix or mux is deployed)

**Comment by cunha** [comment]
Prefix is removed; config autogeneration is implemented. Closing in favor of https://github.com/PEERINGTestbed/client/issues/15.
