### ISSUE TITLE
Clarify help text for ./peering prefix 

### ISSUE THREAD

**Issue by reuteran** [PEERINGTestbed/client#12]
In the help text for the '-c' option it says:

```
-c id       Attach community (47065,id) to the announcement.  This
            will let the announcement through peer with the given
            id.  May be added multiple times to announce **from**
            multiple peers.  [default: announce to all peers]
            (see https://peering.usc.edu/peers for the list of peers)
```

I think that 'from' should be a 'to', right?
Also:

```
[default: announce to all peers]
```

When announcing via: `./peering prefix announce -m amsterdam01 <prefix>` I noticed that not all amsterdam01 peers (according to PEERING website) actually see the prefix.

**Comment by cunha** [comment]
Andreas, how exactly did you check which peers were seeing the prefix?

**Comment by reuteran** [comment]
I looked at RIS/Routeview RIB dumps. Out of the amsterdam01 peers that are also monitors, not all of them actually had a RIB entry for the prefix.
