### ISSUE TITLE
Add notes about using dataplane

### ISSUE THREAD

**Issue by bschlinker** [PEERINGTestbed/client#13]
We should briefly describe how clients can use dataplane by routing traffic through a specific table

**Comment by cunha** [comment]
- explain that if there no default on table 151 (depends on upstreams), then traffic will get routes by the following routing tables (i.e., main)

**Comment by cunha** [comment]
- explain that clients might need to disable RP filtering to allow replies on different interfaces.

**Comment by cunha** [comment]
Closed: https://github.com/PEERINGTestbed/client/wiki/Client-data-plane
