### ISSUE TITLE
Bird Syntax Error

### ISSUE THREAD

**Issue by jaredthecoder** [PEERINGTestbed/client#28]
Hi,

After starting my muxes with `peering openvpn up MUX` for every mux listed in `peering openvpn status`, I then run `peering bgp start`.

However, it then returns this error:
`bird: /home/user/peering/client/configs/bird/bird.conf, line 9: syntax error`

In `configs/bird/bird.conf`, the error is the first `table` line:
```
log "var/bird.log" all;

table rtup;
table igptable;
...
```

The output of `bird --version`: `BIRD version 2.0.2`

I am running on Arch Linux, Kernel 4.15.13-1-ARCH. I installed Bird with `pacman -Sy bird`.

The documentation does not state which bird version you are using. I believe that is the issue.

**Comment by twabulldogg** [comment]
Jared,

Thanks you for submitting the issue.  There were major revisions to the BIRD source code and configure format in 2.0+.  Our configs are formatted for pre-2.0.  If you are able to install v1.6.4, it should work fine.

**Comment by jaredthecoder** [comment]
I was able to and that was the issue. Thanks! I will make a PR specifying that in the docs.
