### ISSUE TITLE
Handle invalid OpenVPN PID file

### ISSUE THREAD

**Issue by bschlinker** [PEERINGTestbed/client#4]
If OpenVPN dies, the PID in the PID file will become invalid.

Right now, `status` checks will always try to send a signal to that PID. However, if that PID is invalid, you get an error like this:
`error [openvpn/logs//tap5.pid exists but cannot send signal]`

**Comment by waehlisch** [comment]
Same for BIRD, btw.

**Comment by cunha** [comment]
OpenVPN exits after checking it does not have permissions to create a tap device, leaves the pidfile around, total class.
